In [1]:
#Task1
import numpy as np
x= np.array([0,1,2,3,4,5,6,7,8,9])
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
#Task2
boolean=np.array([True,True,True,True,True,True,True,True,True])
boolean1=boolean.reshape(3,3)
print(boolean1)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [3]:
#Task3
odd_list=[]
array=np.array([1,2,3,4,5,6,7,8,9,10])
list=array.tolist()
for i in list:
    if i%2==1:
        odd_list.append(i)
        list.remove(i)
new_array=np.asarray(list)
odd_array=np.asarray(odd_list)
print(odd_array)
print(new_array)

[1 3 5 7 9]
[ 2  4  6  8 10]


In [4]:
#Task4
array=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.where(array%2==1,-1,array))

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [5]:
#Task5
array=np.array([1,2,3,4,5,6,7,8])
new_array=array.reshape(2,4)
print(new_array)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
#Task6
a=np.array([1,2,3,4,5,6])
a1=a.reshape(3,2)
b=np.array([1,2,4,5,6,7])
b1=b.reshape(2,3)
c=np.dot(a1,b1)
d=np.sum(c)
print(b1)
print(a1)
print(c)
print(d)

[[1 2 4]
 [5 6 7]]
[[1 2]
 [3 4]
 [5 6]]
[[11 14 18]
 [23 30 40]
 [35 46 62]]
279
