In [1]:
#Task1
import numpy as np
x= np.array([0,1,2,3,4,5,6,7,8,9])
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
#Task2
boolean=np.array([True,True,True,True,True,True,True,True,True])
boolean1=boolean.reshape(3,3)
print(boolean1)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [3]:
#Task3
odd_list=[]
array=np.array([1,2,3,4,5,6,7,8,9,10])
list=array.tolist()
for i in list:
    if i%2==1:
        odd_list.append(i)
        list.remove(i)
new_array=np.asarray(list)
odd_array=np.asarray(odd_list)
print(odd_array)
print(new_array)

[1 3 5 7 9]
[ 2  4  6  8 10]


In [4]:
#Task4
array=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.where(array%2==1,-1,array))


[-1  2 -1  4 -1  6 -1  8 -1 10]


In [5]:
#Task5
array=np.array([1,2,3,4,5,6,7,8])
new_array=array.reshape(2,4)
print(new_array)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
#Task6
a=np.array([1,2,3,4,5,6])
a1=a.reshape(3,2)
b=np.array([1,2,4,5,6,7])
b1=b.reshape(2,3)
c=np.dot(a1,b1)
d=np.sum(c)
print(b1)
print(a1)
print(c)
print(d)

[[1 2 4]
 [5 6 7]]
[[1 2]
 [3 4]
 [5 6]]
[[11 14 18]
 [23 30 40]
 [35 46 62]]
279


In [9]:
#Task7
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8,9])
a1=a.tolist()
b1=b.tolist()
print(a1)
print(b1)
for i in b1:
        if i in a1:
            b1.remove(i)
print(b1) 
new_b=np.asarray(b1)
print(new_b)
            

[1, 2, 3, 4, 5]
[4, 5, 6, 7, 8, 9]
[5, 6, 7, 8, 9]
[5 6 7 8 9]


In [8]:
#Task8
c=[]
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8,9])
a1=a.tolist()
b1=b.tolist()
for i in a1:
        if i>=3 and i<=7:
            c.append(i)   
for j in b1:
    if j>=3 and j<=7:
        c.append(j)
        
new_c=np.asarray(c)
new_c=np.unique(new_c)
print(new_c)

[3 4 5 6 7]
